mailServerFactoryAPI:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: mailServerFactoryAPISecretKey
server:
    port: 8081
spring:
    datasource:
        password: secret
        url: jdbc:postgresql://localhost:5432/UserDB
        username: admin
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
